name: Automatic Add File(s)
on:  
  push:
    branches:
      - master
  schedule:
    - cron: '*/2 * * * *' # every two minutes
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create timestamp 
        id: vars
        run: |
          echo "::set-output name=TIMESTAMP::$(date +'%Y-%m-%d_%H-%M')"
          echo "::set-output name=TS::(date +'%Y-%m-%d_%H-%M-%S')"
          echo "::set-output name=TIZO::$(TZ='Asia/Jakarta' date)"
      - uses: "finnp/create-file-action@master"
        env:
          FILE_NAME: "./timestamp/${{ steps.vars.TIMESTAMP }}.txt"
          FILE_DATA: "${{ steps.vars.outputs.TS }}"
      - name: add and commit
        uses: EndBug/add-and-commit@v7.1.1 
        with:
          add: "./timestamp/${{ steps.vars.outputs.TIMESTAMP }}.txt"
          message: "Update: ${{ steps.vars.outputs.TIZO }}"
